services:
  db:
    container_name: streamer_db
    image: postgres:16-alpine
    restart: 'on-failure'
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_USER: stream
      POSTGRES_DB: db_stream
    volumes:
      - vol_streamer:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    secrets:
      - db_password
secrets:
  db_password:
    file: db_password.txt
volumes:
  vol_streamer:
    external: true